function create_dB_fig(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 03-May-2017 15:26:10

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create xlabel
xlabel('6 dB Levels (with 12 Frequencies)','FontSize',26.4);

% Create ylabel
ylabel('6 dB Levels (with 12 Frequencies)','FontSize',26.4);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 72.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 72.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'FontSize',24,'Layer','top','XTick',...
    [0.5 6.5 12.5 19 24.5 30.5 36.5 42.5 48.5 54.5 60.5 67],'XTickLabel',...
    {'','11','','21','','31','','41','','51','','61'},'YTick',...
    [0.5 6.5 12.5 19 24.5 30.5 36.5 42.5 48.5 54.5 60.5 67],'YTickLabel',...
    {'','11','','21','','31','','41','','51','','61'});
% Create colorbar
colorbar('peer',axes1,'FontSize',21.6);

