function plot_asWavesSorted(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 09-May-2017 15:42:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0.5 36.5]);
% Uncomment the following line to preserve the Y-limits of the axes
ylim(axes1,[0.5 36.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'FontSize',20,'Layer','top','XTick',[1 5 10 14 19 23 28 32],...
    'XTickLabel',{'','Sine','','Square','','Sawtooth','','Triangle'},'YTick',...
    [1 5 10 14 19 23 28 32],'YTickLabel',...
    {'','Sine','','Sqaure','','Sawtooth','','Triangle'});
